import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Navigation from "../components/layout/Navigation";

import "./styles/main.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Catalyst",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navigation />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
